### ISSUE TITLE
Buildable on Windows 11?

### ISSUE THREAD

**Issue by peytonk132** [nealmick/ned#11]
Hi, I had found your repo and I thought I'd try and build. When It came to finding the glfw package, it gave an error saying it couldn't find glfw3Config.cmake

I had cloned the glfw3 repo into the root directory of Ned and built glfw. I had located where the glfw3Config.cmake file was and passed the command to the cmake file in the root Dir, and it gave some other errors, and I was starting to think if maybe this isn't able to be built on Windows. If not, then I can try on WSL but I thought I'd ask to try and save myself from a headache. I also have glfw as well as opengl installed with vcpkg on my machine if that helps.

**Comment by nealmick** [comment]
I have not tested on windows yet, Im on mac currently.   I think its possible to get working on windows but may need some changes or fixes.   I am planning on continuing work on this project soon and will be making builds for different platforms.   The editor works for some basic stuff currently however there are still a good bit of things that need to be improved.  This is mainly just a personal project trying to build an editor, hoping to add more features and improvements as time permits.

**Comment by nealmick** [comment]
As you described cloning the repo with glfw3 into the root directory may not work.  Im not certain but I think this needs to be installed system wide, I used the mac package manager called homebrew.  Its similar to like apt packages for ubuntu.....
https://github.com/nealmick/ned/blob/f43e18fcd52bd88de0e2d2825e03748f256e7a33/CMakeLists.txt#L8

According claude ai:
For Windows, there are several common ways to install GLFW system-wide so CMake's find_package(glfw3 REQUIRED) can work:

Most straightforward method - Install using the Visual Studio Package Manager (vcpkg):
vcpkg install glfw3:x64-windows
Then when running CMake, you need to tell it where to find packages:
cmake .. -DCMAKE_TOOLCHAIN_FILE="C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake"


Alternative approach - Download and install pre-built binaries:

Download the Windows pre-built binaries from the official GLFW site: https://www.glfw.org/download.html
Extract them to a known location (like C:/Program Files/GLFW)
Add the binary location to your system's PATH environment variable
When running CMake, you might need to specify:
cmake .. -DGLFW_DIR="C:/Program Files/GLFW"

Alternative approach - Using a Windows package manager like Chocolatey:
choco install glfw3

**Comment by nealmick** [comment]
okay i added an Ubuntu deb package that can be used on windows via WSL.  Its not perfect but at least it is a start.  I did notice a few issues with colors on windows, for some reason the theme is appearing differently.  I will be working to resolve issues over the coming weeks.
